name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 136.116.214.172
          username: psulfuricacid
          key: ${{ secrets.-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAgEAyJ4LR0po4oSgQPMa5s2HGUDVZYfDTHrnV8dDxuqay/thnk3p8amk
QfJ5oXNAohcK5J9as9NjT87wEt6rS+xik0O2lnKgfX8sx0cj6lNcezobGwTVrBxRM7okvl
rViN/ZnBSTGsrAfxe2KG1rQJUUdkfWJbMqbTW1zwA9dM9vs1BlkhiXfOGVeznnHIDQTEPL
h75YIxiVMLijh25mg4cE2cBbDEYwvw6PnsxM3/N9cYc0r7Zc0b+9dKO40Ke8OlpXvgsPa9
T0G8wkMjdFhH79KtVkq1BG5YpIh3hfgTcfpbbA3oBGbgwk3yzdlDWsR9/QS/0kbWI/jbQ3
l2TGO+cyLA8JEP6Q4EIo5vmeIexl7zL2RoU93/4WoFD+XMD6LkuAJC0ObeVAlbU0jIwVjX
YXUd7ekNFJrCff3tepR2w8JnfU8UtDxhRb7iEWVCqdkywgXHZSG0A3qRobFRupi2UTyCho
LrxZwPiqheVIY32aqTaGzo1HAFS73gA3kyHZTn3qv9BPVxB2o2b53dkw+4zgJt1zS7uCsS
zPIxvZ+X3xUqsGIPi2pmFNo/4xFMzYDyn7Ri4eGgHv+yf8s66qdLeFDxh5L+amcbWKMed5
lE4kagfZOOcb0EWFccRtN5e90Lgbs1bNph8cLuFlW6KMlqUMzJeD6XmXS3hK+3mltzS2XT
EAAAdIP/+3Uz//t1MAAAAHc3NoLXJzYQAAAgEAyJ4LR0po4oSgQPMa5s2HGUDVZYfDTHrn
V8dDxuqay/thnk3p8amkQfJ5oXNAohcK5J9as9NjT87wEt6rS+xik0O2lnKgfX8sx0cj6l
NcezobGwTVrBxRM7okvlrViN/ZnBSTGsrAfxe2KG1rQJUUdkfWJbMqbTW1zwA9dM9vs1Bl
khiXfOGVeznnHIDQTEPLh75YIxiVMLijh25mg4cE2cBbDEYwvw6PnsxM3/N9cYc0r7Zc0b
+9dKO40Ke8OlpXvgsPa9T0G8wkMjdFhH79KtVkq1BG5YpIh3hfgTcfpbbA3oBGbgwk3yzd
lDWsR9/QS/0kbWI/jbQ3l2TGO+cyLA8JEP6Q4EIo5vmeIexl7zL2RoU93/4WoFD+XMD6Lk
uAJC0ObeVAlbU0jIwVjXYXUd7ekNFJrCff3tepR2w8JnfU8UtDxhRb7iEWVCqdkywgXHZS
G0A3qRobFRupi2UTyChoLrxZwPiqheVIY32aqTaGzo1HAFS73gA3kyHZTn3qv9BPVxB2o2
b53dkw+4zgJt1zS7uCsSzPIxvZ+X3xUqsGIPi2pmFNo/4xFMzYDyn7Ri4eGgHv+yf8s66q
dLeFDxh5L+amcbWKMed5lE4kagfZOOcb0EWFccRtN5e90Lgbs1bNph8cLuFlW6KMlqUMzJ
eD6XmXS3hK+3mltzS2XTEAAAADAQABAAACAF0rjRhgVeKxbo2Ledhr5kzTn+elzA1GXQ+W
owMMLLUEO9td2wLZYsgf2N4i3QcKRYxU97ZhO5OyiytwT0SU9VjoTzGC7ccq23x3LRZj/a
TbIQCE18k1Y37u+aaQH/CP6YvDwGfmdszvkbEn0/Ir6lNeXHWoxlDu609GEMShnAI+mdVm
Z2BfkeEnTI6fwl1Q9QLHYz51acA1V/kLTD/UYmvQmlhSdswccpXw0tkFR6KEhPL/8g6Vim
LTsH7zD4dYMry3fUN6pJ4OSlcp9TaqFWChtz2arDppZPLJdC1aEPAQtnT/RPZR3IPrXcK5
xJeiuaW43ISSZuqkIldEvY3PeyxIJpe2HTLuGrLeiRP5KLysWhW7lkrGBhU8m8TVllnlvy
lib0n2IC+uVLG+Vb4p89K6wCt96ML8acZQgT9RuKGcI70VFMEKDylwxL47tmOrRuZb65mT
kUS1kF87UltQEfrj7C9ewizzHP72vJD9gEi0F8oHchI4a1+U0o1LH5ePig4EYZeotYnNbX
fj+oQs6yDoLPhfEJCPxFvHH5Pe7+342AW7+7QKEm5MnpXKP8HChYZCrP2NuZnmRzSJGgV3
sYcygeUwuuTFXOcGfsLz4mZyyC7DyI2PmN3g9tNXCUSsjZMLS5fJoEW/0Cjm8AH5CXl35+
OZ2BLgPPXfeUwisyhLAAABAQD1rWOUk2QDhQzIeY+HT08pjxm1hAlMWnG2qyw1L0F46LpM
qHwcp4m9JTt4ZZBAeUOUUPma8c6hL2y1Z8eoa5HekTEl/EDiqGihvMhEshw46+YqUU6l6z
45DETeHJ7GkH/gO39dNerFVuaF9Oo9kjA7UH8CE2KPCngg+I+XWdz+W5kVfEk293IMK4R1
1kow3ns1QJ7hDkxB1jtbMNIBruoQXsNVdT9ui/fcC8ihDKFeVqDq6CO5BCF35UvTDMjdQQ
oZWsAy4QOzRxjluBsf+HG40rmvQ4iMxCcK8wKzGvBgcG6/yuB0YWZBS0qUGPAmdOkCPX8O
lTMQldFJWD6bR+8GAAABAQD+qjD7lBNwEWbUvqpOdbn9CuTM0HPMkKWz76M6dhX3mF7Pgp
asMWjGlBNaTV/MS3TSUU2oiz/5RIYZUd8U4a9J0/OptvIxhvPEoVbFV7BVhEhVYr2UJvXl
jZdEoAl2uDD3zTdN4di0cN9uqJ/EqL6dkLIdYEJL86A8Pdj6oZxcATNQEitaicGEgRBs4m
ClU7f4XvXFmiN6n7drNNi12Pi4IyBP+uBPPolJAn8hQ5voPkrCZ223ExYGENpKS7k/lBgw
gtEe9VFMDObL2lss0FcMdV6q1Ht1Ds9QKK09D/cBtwH3XhtpWEiYmGMFCABt4WR2inm1Al
D6GiBRWKCuzvrLAAABAQDJq0+NQpgDn3FdMFwKJc3J7dZGFaJstDuZYK+MDIEGx9Zxa30l
gKhhKxOvxiFcUJL9bgSPWeQ7/ZwjXWkH+9xNZRM06D26FEU5M3BlDaOKUDcCqP7lZlnDvX
cUhT1tvlCCXQaa+GmMgVPnWPFBK7KrfrZdL6WmqdXuP3HQNQt6CpLvk/nEoEIrWbvg1l+Y
Xpc7MRrk9Oh7KEEQPsIlSTUH4n0lOGgztQ/bcK7SBH4SKMUzumfSPXXNSyjTpYBhOBe2dX
zOXG/L9HtUKYVNghiZVpebvpdumBsupgd9Rb8NHuxVrYelhwJuUHUxfhpJwy2cUFSBi5CV
ctFsG9qBuJxzAAAADmdpdGh1Yi1hY3Rpb25zAQIDBA==
-----END OPENSSH PRIVATE KEY----- }}
          script: |
            cd ~/devops-dockerized-backend
            ./deploy.sh
